services:
  web:
    build: ./SakanaCDN
    volumes:
      - uploads:/home/SakanaCDN/web/uploads
      - db_data:/home/SakanaCDN/web/instance
    expose:
      - 5000
  nginx:
    build: ./nginx
    ports:
      - 5000:5000
    depends_on:
      - web

volumes:
  uploads:
  db_data:
