services:
  web:
    build: ./SakanaStorage
    volumes:
      - uploads:/home/SakanaStorage/web/uploads
      - db_data:/home/SakanaStorage/web/instance
      - logs:/home/SakanaStorage/web/logs
    expose:
      - 5000

  nginx:
    build: ./nginx
    ports:
      - 5000:5000
    depends_on:
      - web

volumes:
  uploads:
  db_data:
  logs:
