services:
  web:
    build: ./SakanaCDN
    volumes:
      - data_volume:/home/SakanaCDN/web
    expose:
      - 5000
  nginx:
    build: ./nginx
    ports:
      - 5000:5000
    depends_on:
      - web

volumes:
  data_volume:
